apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-sample-app
  namespace: default  # Añadir el namespace aquí
  labels:
    app: argo-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-sample-app
  template:
    metadata:
      labels:
        app: argo-sample-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
