apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
      - name: html-container
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        hostPath:
          path: /app/html-site
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
