apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: default  # Namespace donde se desplegará el recurso
spec:
  type: LoadBalancer
  selector:
    app: html-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
